modLoader="javafxmod"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="nullpointermod"
version="${file.jarVersion}"
displayName="Null Pointer Mod"
displayURL="https://github.com/Hualuomao/nullpointermod"
logoFile="assets/nullpointermod/logo.png"
credits="Created by Hualuomao"
authors="Hualuomao"
description="""A Minecraft mod that adds the Java Item and Null Pointer Projectile.
When you right-click on air with the Java Item, it generates a Null Pointer.
When you right-click with the Null Pointer, it shoots a projectile that crashes the client when it hits something.
"""

[[dependencies.nullpointermod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nullpointermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
